---
openapi: 3.0.0
info:
  title: OEM Sponsor API - Documentation
  description: "This document is for OEM Sponsor API\n\n_Author: Hung Do at [hung.do@traderinteractivec.com]()_\n\nSome useful links:\n- "
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- url: https://mqzvz91b2d.execute-api.us-east-1.amazonaws.com
paths:
  /sponsors:
    get:
      summary: Find all sponsors
      description: Find
      operationId: findAllOEMSponsors
      parameters:
      - name: Control-Allow-Origin
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad request. User ID must be an integer and larger than 0.
        "401":
          description: Authorization information is missing or invalid.
        "404":
          description: A user with the specified ID was not found.
        "5XX":
          description: Unexpected error.
      security:
      - bearerAuth: []
  /token:
    post:
      tags:
      - token
      summary: Create an access token.
      description: Attempts to get an access token for the user.
      operationId: TokenController::postAction
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/token_body'
        required: true
      responses:
        "200":
          description: Returns a token for the user.
        "400":
          description: Returned for invalid credentials / bad request.
      servers:
      - url: https://api-proto.auth.us-east-1.amazoncognito.com/oauth2
        description: Override base path for all operations with the /files path
components:
  schemas:
    token_body:
      type: object
      properties:
        grant_type:
          type: string
          description: OAuth 2.0 Authorization Grant Type.
          example: client_credentials
        client_id:
          type: string
          description: Your Media API Client ID.
        client_secret:
          type: string
          description: Your Media API Client secret.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
